apiVersion: v1
kind: BuildConfig
metadata:
  name: pipeline-welcome
  namespace: cicd
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: >-

        node('maven') {

        stage 'Build In Dev'

        openshiftBuild(namespace: 'development', buildConfig: 'welcome',
        showBuildLogs: 'true')

        stage 'Deploy In Dev'

        openshiftDeploy(namespace: 'development', deploymentConfig: 'welcome')

        openshiftScale(namespace: 'development', deploymentConfig:
        'welcome',replicaCount: '2')

        stage ('Deploy In Stage'){
            timeout(time:5, unit:'MINUTES') {
                input message: "Promote to Stage?", ok: "Promote"
            }
        }

        sh "oc tag development/welcome:latest testing/welcome:promoteToQA"

        sh "oc project testing"
        // clean up. keep the imagestream

        sh "oc delete bc,dc,svc,route -l app=welcome -n testing"
        // deploy stage image

        sh "oc new-app welcome:promoteToQA -n testing"
 
        sh "oc expose svc/welcome -n testing"  


        openshiftScale(namespace: 'testing', deploymentConfig:
        'welcome',replicaCount: '3')

        }
  output: {}
  resources: {}
  postCommit: {}
  nodeSelector: null
