apiVersion: v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  namespace: cicd
  selfLink: /oapi/v1/namespaces/cicd/buildconfigs/myfirstpipeline
  uid: 753ffb15-718a-11e7-b1ca-be5867782ab0
  resourceVersion: '6477'
  creationTimestamp: '2017-07-25T22:41:54Z'
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "welcome", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: >-

        node('maven') {

        stage 'Build In Dev'

        openshiftBuild(namespace: 'development', buildConfig: 'welcome',
        showBuildLogs: 'true')

        stage 'Deploy In Dev'

        openshiftDeploy(namespace: 'development', deploymentConfig: 'welcome')

        openshiftScale(namespace: 'development', deploymentConfig:
        'welcome',replicaCount: '2')

        stage ('Deploy In Stage'){
            timeout(time:5, unit:'MINUTES') {
                input message: "Promote to Stage?", ok: "Promote"
            }
        }

        openshiftTag(namespace: 'development', sourceStream: 'welcome', 
        sourceTag: 'latest', destinationStream: 'welcome', destinationTag:
        'promoteToQA')

        openshiftDeploy(namespace: 'testing', deploymentConfig: 'welcome', )

        openshiftScale(namespace: 'testing', deploymentConfig:
        'welcome',replicaCount: '3')

        }
  output: {}
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 2
